# Generated by Django 2.1.7 on 2019-05-11 22:12

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='MyPermission',
            fields=[
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permission',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.MyUser', verbose_name='Author')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Photo Profile')),
                ('gender', models.CharField(blank=True, max_length=30, null=True, verbose_name='Gender')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('place_of_birth', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('birth_date', models.CharField(blank=True, max_length=20, null=True)),
                ('redirect_url', models.CharField(blank=True, default='admin:index', max_length=255, null=True, verbose_name='Default redirect URL')),
                ('web_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Web Site')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook Page')),
                ('twitter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter Page')),
                ('google_plus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Plus Page')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram Page')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profile',
                'db_table': 'ant_profile',
            },
        ),
    ]
