# Generated by Django 5.2.5 on 2025-09-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_category', to='filemedia.category'),
        ),
    ]
