# Generated by Django 5.2.5 on 2025-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemedia', '0002_alter_media_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extensions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
