# Generated by Django 5.2.5 on 2025-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemedia', '0003_category_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
