# Generated by Django 5.2.5 on 2025-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemedia', '0004_media_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='extensions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
