# Generated by Django 5.2.5 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemedia', '0005_alter_category_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
            ],
            options={
                'verbose_name': 'File Manager',
                'verbose_name_plural': 'File Manager',
                'permissions': (('get_image_ajax', 'Can get image (ajax)'), ('change_image_ajax', 'Can change upload image (ajax)'), ('upload_image_ajax', 'Can upload image (ajax)'), ('delete_image_ajax', 'Can delete image (ajax)'), ('download_image', 'Can download image')),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('filemedia.media',),
        ),
        migrations.AlterField(
            model_name='category',
            name='extensions',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
