# Generated by Django 5.0 on 2024-10-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('content', models.TextField(default='Content', null=True)),
                ('type', models.CharField(blank=True, default='general', max_length=255)),
                ('autoload', models.CharField(blank=True, default='yes', max_length=3)),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'setting',
                'db_table': 'ant_setting',
                'permissions': (('get_theme_ajax_setting', 'Can get theme settings (ajax)'), ('change_theme_ajax_setting', 'Can change theme settings (ajax)'), ('user_password_change', 'Can change user password'), ('profile_change', 'Can change user profile'), ('theme_setting', 'Can change user admin theme setting'), ('index_view', 'Can view home index')),
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'admin setting',
                'verbose_name_plural': 'admin setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nifty.setting',),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nifty.setting',),
        ),
    ]
