# Generated by Django 5.0 on 2024-10-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('nifty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiftyLogEntry',
            fields=[
                ('log_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin.logentry')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'log entry',
                'db_table': 'ant_logentry',
            },
        ),
    ]
