# Generated by Django 5.2.5 on 2025-09-23 11:44

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('nifty', '0003_delete_niftylogentry_niftylogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NiftyLogEntry',
        ),
        migrations.CreateModel(
            name='LogEntrys',
            fields=[
            ],
            options={
                'verbose_name': 'log entry',
                'verbose_name_plural': 'log entry',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
