# Generated by Django 5.2.5 on 2025-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageQualityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configs', models.JSONField(default=dict, help_text="Konfigurasi kualitas gambar, contoh: {'default': {'defaultQuality': 70}, 'png': {'defaultQuality': 90}}")),
            ],
        ),
    ]
