# Generated by Django 5.2.5 on 2025-10-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbox', '0002_imagequalityconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
