# Generated by Django 5.2.5 on 2025-10-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbox', '0003_workspacegroup_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
