# Generated by Django 5.2.5 on 2025-09-18 15:43

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(help_text='A short label, generally used in URLs.', max_length=35, null=True, verbose_name='Slug')),
                ('status', models.BooleanField(default=True, help_text='Status is checked will be published.', max_length=1, verbose_name='Status')),
                ('type', models.CharField(max_length=25, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Position')),
                ('menu_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Menu Type')),
                ('root', models.IntegerField(blank=True, null=True, verbose_name='Root')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.taxonomy', verbose_name='Parent')),
            ],
            options={
                'db_table': 'ant_taxonomy',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(help_text='A short label, generally used in URLs.', max_length=255)),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('type', models.CharField(max_length=25, verbose_name='Type')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('t', 'Trash')], max_length=1, verbose_name='Status')),
                ('comment_status', models.BooleanField(default=False, help_text='Is checked will be actived on prontand.', max_length=1, verbose_name='Allow comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('page', models.TextField(blank=True, null=True)),
                ('word_meta', models.TextField(blank=True, null=True)),
                ('layout', models.CharField(choices=[('none', 'None'), ('right', 'Sidebar Right'), ('left', 'Sidebar Left'), ('pull', 'Pull')], max_length=255, verbose_name='Layout')),
                ('relationships', mptt.fields.TreeManyToManyField(blank=True, db_column='word_id', db_table='ant_word_relationships', to='word.taxonomy', verbose_name='Relationships')),
                ('self_relationships', models.ManyToManyField(blank=True, db_table='ant_self_relationships', to='word.word', verbose_name='Self Relationships')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'db_table': 'ant_word',
            },
        ),
    ]
