# Generated by Django 5.2.5 on 2025-10-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentconfig',
            name='ckbox_project_id',
            field=models.CharField(blank=True, help_text='CKBox Project ID / Audience', max_length=255, null=True),
        ),
    ]
