"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 5.0

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from django.conf.locale.es import formats
from django.utils.translation import gettext_lazy as _
from nifty import VERSION

formats.DATETIME_FORMAT = '%b. %d, %Y, %I:%M %p'

# html to Pdf
path_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p#9)0ixeb6*e8=gi45--#gz#0e+k4yn59_e4g_^vtkgu8f@x%m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'auth.user'
# Application definition
DATETIME_FORMAT = 'Y-m-d H:i:sO'
INSTALLED_APPS = [
    'nifty',
    'django.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'filemedia',
    'users',
    'debug_toolbar',
]

NIFTY_SETTING = {
    'VERSION': VERSION,
    # configurable
    'ADMIN_NAME': 'Django NiFty',
    'HEADER_DATE_FORMAT': 'l, jS F Y',
    'HEADER_TIME_FORMAT': 'H:i',
    # form
    'SHOW_REQUIRED_ASTERISK': True,
    'CONFIRM_UNSAVED_CHANGES': True,
    # menu
    'SEARCH_URL': '/admin/auth/user/',
    'MENU_OPEN_FIRST_CHILD': True,
    'MENU_ICONS': {
        'users': 'demo-pli-male',
        'sites': 'icon-leaf',
    },
    # 'MENU_EXCLUDE': ('auth.group',),
    'MENU': (
        # 'sites',
        {'label': _('Dashboard'), 'permissions': 'admin.index_view', 'icon': 'demo-pli-home', 'url': 'admin:index'},
        {'app': 'filemedia', 'icon': 'demo-pli-layout-grid', 'models': ('filemedia.tags', 'filemedia.file', 'filemedia.image', 'filemedia.video',)},
        {'app': 'users', 'icon': 'demo-pli-male', },
        '-',
        {'app': 'nifty', 'icon': 'demo-pli-information', 'label': _('Administration'), 'models': ('nifty.admin', 'nifty.site', 'nifty.logentrys',)},
    ),
    # Menu Users
    'MENU_USERS': (
        {'label': _('My Profile'), 'permissions': 'admin.profile_change', 'icon': 'demo-pli-male', 'url': 'admin:profile'},
        {'label': _('Theme Settings'), 'permissions': 'admin.theme_setting', 'icon': 'demo-pli-split-vertical-2', 'url': 'admin:theme_settings'},
        {'label': _('Change Password'), 'permissions': 'admin.user_password_change', 'icon': 'demo-pli-repair', 'url': 'admin:password_change'},
    ),
    'MENU_USERS_ICONS': {},
    'MENU_USERS_EXCLUDE': (),
    'MENU_USERS_OPEN_FIRST_CHILD': True,
    'MENU_USERS_ORDER': (),
    # Menu Header
    'MENU_HEADER': (
        {'label': _('Home'), 'permissions': 'admin.index_view', 'icon': 'demo-pli-home', 'url': 'admin:index'},
        {'app': 'filemedia', 'icon': 'demo-pli-layout-grid', 'models': ('filemedia.tags', 'filemedia.file', 'filemedia.image', 'filemedia.video',)},
        {'app': 'users', 'icon': 'demo-pli-male', },
        {'app': 'admin', 'icon': 'demo-pli-information', 'models': ('admin.admin', 'admin.site', 'admin.logentry',)},
    ),
    'MENU_HEADER_ICONS': {},
    'MENU_HEADER_EXCLUDE': (),
    'MENU_HEADER_OPEN_FIRST_CHILD': True,
    'MENU_HEADER_ORDER': (),
    # Menu Users Header
    'MENU_USER_HEADER': (
        {'label': _('My Profile'), 'permissions': 'admin.profile_change', 'icon': 'demo-pli-male', 'url': 'admin:profile'},
        {'label': _('Theme Settings'), 'permissions': 'admin.theme_setting', 'icon': 'demo-pli-split-vertical-2', 'url': 'admin:theme_settings'},
        {'label': _('Change Password'), 'permissions': 'admin.user_password_change', 'icon': 'demo-pli-repair', 'url': 'admin:password_change'},
        {'label': 'Django Doc', 'icon': 'demo-pli-file', 'url': 'django-admindocs-docroot'},
        {'label': _('Logout'), 'icon': 'demo-pli-unlock', 'url': 'admin:logout', 'logout': True},
    ),
    'MENU_USER_HEADER_ICONS': {},
    'MENU_USER_HEADER_EXCLUDE': (),
    'MENU_USER_HEADER_OPEN_FIRST_CHILD': True,
    'MENU_USER_HEADER_ORDER': (),

    # Menu Shortcut
    'MENU_SHORCUT': (
        {'label': _('My Profile'), 'style': 'bg-mint', 'icon': 'demo-pli-male', 'url': '#'},
        {'label': _('Messages'), 'style': 'bg-warning', 'icon': 'demo-pli-speech-bubble-3', 'url': '#'},
        {'label': _('Settings'), 'style': 'bg-success', 'icon': 'demo-pli-thunder', 'url': '#'},
        {'label': _('Documentation'), 'style': 'bg-purple', 'icon': 'demo-pli-file', 'url': '#'},
    ),
    'MENU_SHORCUT_ICONS': {},
    'MENU_SHORCUT_EXCLUDE': (),
    'MENU_SHORCUT_OPEN_FIRST_CHILD': True,
    'MENU_SHORCUT_ORDER': (),
    # misc
    'LIST_PER_PAGE': 24
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'web.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'users/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nifty.context.site',
                'nifty.context.admin_theme',
                'nifty.context.log_entry_results',
                'nifty.context.admin',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGES = [
    ('en', 'English'),
    ('id', 'Indonesia'),
]
LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_ROOT = BASE_DIR + os.sep + 'static' + os.sep
# STATIC_URL = '/static/'
#
# MEDIA_ROOT = BASE_DIR + os.sep + 'media' + os.sep
# MEDIA_URL = '/media/'

STATIC_ROOT = BASE_DIR + os.sep + 'static' + os.sep
STATIC_URL = '/static/'

MEDIA_ROOT = BASE_DIR + os.sep + 'media' + os.sep
MEDIA_URL = '/media/'

LOCALE_PATHS = (
    os.path.join(os.path.dirname(__file__), "../locale"),
)

INTERNAL_IPS = '127.0.0.1'
# DEBUG_TOOLBAR_PANELS = [
#     'debug_toolbar.panels.versions.VersionsPanel',
#     'debug_toolbar.panels.timer.TimerPanel',
#     'debug_toolbar.panels.settings.SettingsPanel',
#     'debug_toolbar.panels.headers.HeadersPanel',
#     'debug_toolbar.panels.request.RequestPanel',
#     'debug_toolbar.panels.sql.SQLPanel',
#     'debug_toolbar.panels.staticfiles.StaticFilesPanel',
#     'debug_toolbar.panels.templates.TemplatesPanel',
#     'debug_toolbar.panels.cache.CachePanel',
#     'debug_toolbar.panels.signals.SignalsPanel',
#     'debug_toolbar.panels.logging.LoggingPanel',
#     'debug_toolbar.panels.redirects.RedirectsPanel',
# ]
